name: "Hello world"
description: "Meine 1. App."
version: "1.0.14"
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: manual
init: false
webui: "http://[HOST]:[PORT:5000]"
watchdog: "http://[HOST]:5000/health"
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web Interface
options:
  require_login: false
  admin_username: "root"
  admin_password: ""
schema:
  require_login: bool
  admin_username: str
  admin_password: password
map:
  - type: addon_config
    read_only: false
    path: /config